language: node_js

services:
    - xvfb

node_js:
    - "10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
env:
  - CXX=g++-4.8

install:
    - npm install
    - npm install codecov -g

script:
  - npm run coverage:ci
  - codecov
  - npm run dist

deploy:
  # Deploy config for non-tag branches
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi.js"
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    cache_control: "max-age=60"
    local_dir: dist
    upload-dir: "$TRAVIS_BRANCH"
    on:
        all_branches: true
        condition: -z $TRAVIS_TAG
  # Deploy config for tagged releases
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi.js"
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    cache_control: "max-age=2592000"
    local_dir: dist
    upload-dir: "$TRAVIS_BRANCH"
    on:
        all_branches: true
        condition: $TRAVIS_TAG
  # Deploy config for latest release
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi.js"
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    cache_control: "max-age=1209600"
    local_dir: dist
    upload-dir: "release"
    on:
        all_branches: true
        condition: $TRAVIS_TAG
