sudo: false
language: node_js
node_js:
    - "4"

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test
